version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: track-finan-api
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - trackfinannet

  postgres:
    image: postgres
    volumes:
      - my_postgres:/var/lib/postgresql/data
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "trackfinan"
    ports:
      - "5432:5432"
    networks:
      - trackfinannet

  # loki:
  #   image: grafana/loki:2.7.5
  #   ports:
  #     - "3100:3100"
  #   command: 
  #     - config.file=/etc/loki/local-config.yaml
  #     - print-config-stderr=true
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/loki-config.yaml
  #   networks:
  #     - trackfinannet

  # promtail:
  #   image: grafana/promtail:2.7.5
  #   volumes:
  #     - ./promtail/config/config.yaml:/etc/promtail/config.yaml
  #     - '/var/logs:/logs/syslogs'
  #     - ./logs:/logs 
  #     - './promtail/position:/position'
  #   ports: 
  #     - 9080:9080
  #   depends_on:
  #     - loki
  #     - app
  #   networks:
  #     - trackfinannet

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - loki
  #   networks:
  #     - trackfinannet
  
networks:
  trackfinannet:
    driver: bridge

volumes:
  my_postgres: