FROM node:18

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

RUN npm install -g @nestjs/cli

# Copiar apenas os arquivos de dependência primeiro
COPY package*.json ./
RUN npm install

# Não vamos copiar o código fonte aqui, pois será montado via volume
EXPOSE 8080

CMD [ "npm", "run", "start:dev" ]