### Teste de Rota: Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123"
}

### Teste de Rota: Obter Perfil do Usuário
GET http://localhost:8080/auth/profile
Authorization: Bearer {token}

### Teste de Rota: Refresh Token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refresh_token": "{refresh_token}"
}
