### Teste de Rota: Criar Usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "admin8@trackfinance.com",
  "password": "admin",
  "fullName": "Admin"
}

### Teste de Rota: Obter Todos os Usuários
GET http://localhost:3000/users

### Teste de Rota: Obter Usuário por ID
GET http://localhost:3000/users/01J986Z9GKYPVN1JJ0TTJ8DDTS

### Teste de Rota: Atualizar Usuário
PUT http://localhost:3000/users/01J986Z9GKYPVN1JJ0TTJ8DDTS
Content-Type: application/json

{
  "fullName": "John Doe Updated",
  "password": "newSecurePassword123"
}

### Teste de Rota: Remover Usuário
DELETE http://localhost:3000/users/01J986Z9GKYPVN1JJ0TTJ8DDTS