### Teste de Rota: Criar Usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123",
  "fullName": "Teste User"
}

### Teste de Rota: Obter Todos os Usuários
GET http://localhost:8080/users

### Teste de Rota: Obter Usuário por ID
GET http://localhost:8080/users/01J986Z9GKYPVN1JJ0TTJ8DDTS

### Teste de Rota: Atualizar Usuário
PUT http://localhost:8080/users/01J986Z9GKYPVN1JJ0TTJ8DDTS
Content-Type: application/json

{
  "fullName": "John Doe Updated",
  "password": "newSecurePassword123"
}

### Teste de Rota: Remover Usuário
DELETE http://localhost:8080/users/01J986Z9GKYPVN1JJ0TTJ8DDTS